name: test_gen_ai
description: >
  An LLM-based test generation tool that generates Dart test cases for uncovered code
  using Google Gemini to improve code coverage.
version: 0.1.0
repository: https://github.com/AmrAhmed119/dart-testgen
issue_tracker: https://github.com/AmrAhmed119/dart-testgen/issues

environment:
  sdk: '>=3.9.0 <4.0.0'

topics:
  - testing
  - code-coverage
  - gemini
  - llm
  - automation

dependencies:
  analyzer: ^9.0.0
  args: ^2.7.0
  collection: ^1.19.1
  coverage: ^1.15.0
  dotenv: ^4.2.0
  google_generative_ai: ^0.4.7
  logging: ^1.3.0
  package_config: ^2.2.0
  path: ^1.9.1
  stack_trace: ^1.12.1
  yaml: ^3.1.3

dev_dependencies:
  benchmark_harness: ^2.4.0
  build_runner: ^2.10.5
  http: ^1.6.0
  lints: ^6.0.0
  mockito: ^5.6.3
  test: ^1.29.0

executables:
  testgen: 